title: joseph's page
url: https://jomolin.github.io
baseurl: /page
author: Joseph
email: jsmolinelli@proton.me
description: my little room online

permalink: /blog/:title/

collections:
  garden:
    output: true
    permalink: /garden/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: garden
    values:
      layout: page
  - scope:
      path: ""
    values:
      layout: default

titles_from_headings:
  enabled: false

relative_links:
  enabled: false

plugins:
  - jekyll-feed

feed:
  collections:
    - posts